### ISSUE TITLE
interactive shell not working in 2.0.0

### ISSUE THREAD

**Issue by devopstales** [devopstales/KubeDash#28]
It Dose not work behind proxy.
```
[2023-06-07 09:35:46 +0200] [13] [ERROR] Socket error processing request.
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/gthread.py", line 271, in handle
    keepalive = self.handle_request(req, conn)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/gthread.py", line 343, in handle_request
    util.reraise(*sys.exc_info())
  File "/usr/local/lib/python3.11/site-packages/gunicorn/util.py", line 626, in reraise
    raise value
  File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/gthread.py", line 329, in handle_request
    resp.write(item)
  File "/usr/local/lib/python3.11/site-packages/gunicorn/http/wsgi.py", line 326, in write
    self.send_headers()
  File "/usr/local/lib/python3.11/site-packages/gunicorn/http/wsgi.py", line 322, in send_headers
    util.write(self.sock, util.to_bytestring(header_str, "latin-1"))
  File "/usr/local/lib/python3.11/site-packages/gunicorn/util.py", line 287, in write
    sock.sendall(data)
OSError: [Errno 9] Bad file descriptor
```

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/eventlet/queue.py", line 118, in switch
    self.greenlet.switch(value)
greenlet.error: cannot switch to a different thread
````

**Comment by devopstales** [comment]
Same problem as in https://github.com/devopstales/KubeDash/issues/29. The main cause of this is the usage of gunicorn and a bug in gunicprn that has been fixed in https://github.com/benoitc/gunicorn/issues/2828 and https://github.com/benoitc/gunicorn/pull/2581 but not yet been release.
